// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
  
  }

  interface StaticRouter {
    "/confidentialite": StaticRoute;
    "/contact": StaticRoute;
    "/demo": StaticRoute;
    "/mentions-legales": StaticRoute;
    "/pricing": StaticRoute;
    "/auth/error": StaticRoute;
    "/auth/forgot-password": StaticRoute;
    "/auth/login": StaticRoute;
    "/auth/onboarding": StaticRoute;
    "/auth/register": StaticRoute;
    "/auth/reset-password": StaticRoute;
    "/auth/verify": StaticRoute;
    "/auth/verify/pending": StaticRoute;
    "/auth/verify/success": StaticRoute;
    "/dashboard/companies/[id]/edit": StaticRoute;
    "/dashboard/companies/[id]/employees": StaticRoute;
    "/dashboard/companies/[id]": StaticRoute;
    "/dashboard/companies/new": StaticRoute;
    "/dashboard/companies": StaticRoute;
    "/dashboard/contracts/[id]/edit": StaticRoute;
    "/dashboard/contracts/[id]": StaticRoute;
    "/dashboard/contracts/create": StaticRoute;
    "/dashboard/contracts/new": StaticRoute;
    "/dashboard/contracts": StaticRoute;
    "/dashboard/diagnostics": StaticRoute;
    "/dashboard/documents": StaticRoute;
    "/dashboard/employees/[id]/edit": StaticRoute;
    "/dashboard/employees/[id]/generate": StaticRoute;
    "/dashboard/employees/[id]/history": StaticRoute;
    "/dashboard/employees/[id]": StaticRoute;
    "/dashboard/employees/[id]/payslips": StaticRoute;
    "/dashboard/employees/create": StaticRoute;
    "/dashboard/employees": StaticRoute;
    "/dashboard/guide": StaticRoute;
    "/dashboard/onboarding": StaticRoute;
    "/dashboard": StaticRoute;
    "/dashboard/payslips/[id]/edit": StaticRoute;
    "/dashboard/payslips/[id]": StaticRoute;
    "/dashboard/payslips/create": StaticRoute;
    "/dashboard/payslips/generate": StaticRoute;
    "/dashboard/payslips": StaticRoute;
    "/employees": StaticRoute;
    "/enterprises": StaticRoute;
    "/faq": StaticRoute;
    "/": StaticRoute;
    "/payments": StaticRoute;
    "/payslip/new": StaticRoute;
    "/payslip": StaticRoute;
    "/payslips/[id]": StaticRoute;
    "/payslips/create": StaticRoute;
    "/payslips": StaticRoute;
    "/profile": StaticRoute;
    "/tarifs": StaticRoute;
  }
}
